/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasifoodcourt;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Windows 7
 */
public class FrmLoginPelayan extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps;
    int ctr;
    Statement st;
    ResultSet rs;
    String query;
    Timer timer;
    String id = UserID.getId();
        
    
    /**
     * Creates new form LoginPelayan
     */
    public FrmLoginPelayan() {
        initComponents();
        
        FrmLoginPelayan frm = this;
        // Timer untuk Notifikasi
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcourt", 
                            "root", "");
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(FrmLoginMaster.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                query = "SELECT COUNT(b.IdMenu)FROM tbltransaksi a, tblrinciantransaksi b "
                        + "WHERE a.IdTransaksi = b.IdTransaksi AND a.IdPelayan = ? AND b.Status = 'siap'";
        
                try {
                        ps = conn.prepareStatement(query);
                        ps.setString(1, id);
                        rs = ps.executeQuery();
                        rs.next();
                        int jum = rs.getInt(1);
                        System.out.print(jum);
                        lblJumSiap.setText("Jumlah Siap : " + jum);
                        if (jum != 0) {
                            playSound();
                        } 
                } catch (SQLException ex) {
                        Logger.getLogger(FrmLoginMaster.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }, 100, 10*1000);
    }
    
    private void playSound() {
        File url = new File("beep.wav");
        Clip clip;
        try {
            clip = AudioSystem.getClip();
            AudioInputStream ais = AudioSystem.
            getAudioInputStream(url);
        clip.open(ais);
        clip.loop(1);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
            }
        });
        } catch (LineUnavailableException ex) {
            Logger.getLogger(FrmLoginPelayan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(FrmLoginPelayan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmLoginPelayan.class.getName()).log(Level.SEVERE, null, ex);
        }
        // getAudioInputStream() also accepts a File or InputStream
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSiap = new javax.swing.JButton();
        btnPesanan = new javax.swing.JButton();
        lblJumSiap = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (2).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 210, 290));

        jLabel1.setBackground(new java.awt.Color(0, 204, 51));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PELAYAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 50));

        btnSiap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSiap.setText("ORDER SIAP DIHIDANGKAN");
        btnSiap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiapActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiap, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 50));

        btnPesanan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesanan.setText("PEMESANAN MENU");
        btnPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesananActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 50));

        lblJumSiap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblJumSiap, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 120, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelayan foodcourt.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 220, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananActionPerformed
        // TODO add your handling code here:
        FrmPesanan fr = new FrmPesanan();
        fr.setVisible(true);
        this.dispose();
        timer.cancel();
    }//GEN-LAST:event_btnPesananActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        FrmLoginMaster fr = new FrmLoginMaster();
        fr.setVisible(true);
        timer.cancel();
    }//GEN-LAST:event_formWindowClosing

    private void btnSiapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiapActionPerformed
        // TODO add your handling code here:
        FrmSiap fr = new FrmSiap();
        fr.setVisible(true);
        this.dispose();
        timer.cancel();
    }//GEN-LAST:event_btnSiapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginPelayan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginPelayan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginPelayan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginPelayan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginPelayan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesanan;
    private javax.swing.JButton btnSiap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblJumSiap;
    // End of variables declaration//GEN-END:variables
}
