/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasifoodcourt;

import java.awt.Color;

/**
 *
 * @author Windows 7
 */
public class FrmLoginManagerFC extends javax.swing.JFrame {

    /**
     * Creates new form LoginManagerFC
     */
    public FrmLoginManagerFC() {
        initComponents();
    }
    
    public FrmLoginManagerFC(String id) {
        initComponents();
        Color putih = new Color(255,255,255,125);
        jPanel1.setBackground(putih);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntryPegawai = new javax.swing.JButton();
        btnEntryVendor = new javax.swing.JButton();
        btnEntryUser = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGER FOODCOURT");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 270, 40));

        btnEntryPegawai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntryPegawai.setText("ENTRY PEGAWAI");
        btnEntryPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntryPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntryPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 30));

        btnEntryVendor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntryVendor.setText("ENTRY VENDOR");
        btnEntryVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntryVendorActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntryVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 177, 30));

        btnEntryUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntryUser.setText("ENTRY USER VENDOR");
        btnEntryUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntryUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntryUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 177, 30));

        btnLaporan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLaporan.setText("LAPORAN PENDAPATAN");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        FrmLoginMaster fr = new FrmLoginMaster();
        fr.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnEntryPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntryPegawaiActionPerformed
        // TODO add your handling code here:
        FrmPegawai fr = new FrmPegawai();
        fr.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnEntryPegawaiActionPerformed

    private void btnEntryVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntryVendorActionPerformed
        // TODO add your handling code here:
        FrmVendor fr = new FrmVendor();
        fr.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnEntryVendorActionPerformed

    private void btnEntryUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntryUserActionPerformed
        // TODO add your handling code here:
        FrmUser fr = new FrmUser();
        fr.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnEntryUserActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        FrmLaporanFC fr = new FrmLaporanFC();
        fr.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginManagerFC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntryPegawai;
    private javax.swing.JButton btnEntryUser;
    private javax.swing.JButton btnEntryVendor;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
