/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasifoodcourt;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;
import java.awt.Color; 
import java.awt.Graphics; 
import java.awt.Graphics2D; 
import javax.swing.JPanel;


/**
 *
 * @author Windows 7
 */

public class FrmLoginMaster extends javax.swing.JFrame {


    Connection conn;
    PreparedStatement ps;
    int ctr;
    Statement st;
    ResultSet rs;
    
    /**
     * Creates new form MasterFoodcourt
     */
    public FrmLoginMaster() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcourt", 
                    "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmLoginMaster.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmLoginMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Color putih = new Color(255,255,255,150);
        jPanel1.setBackground(putih);
        jPanel2.setBackground(putih);
        
    }
    
    private void login() {
        String query;
        String DBHash = "";
        String id = "";
        String fungsi = "";
        String enteredHash = "";
        String username = tflUsername.getText();
        String password = new String(pflPassword.getPassword());
        
        
        // MD5 Hashing
        MessageDigest md;
        try {
            md = MessageDigest.getInstance("MD5");
            md.update(password.getBytes());
            byte[] digest = md.digest();
            enteredHash = DatatypeConverter.printHexBinary(digest).toUpperCase();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(FrmLoginMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        query = "SELECT a.Password, a.Id, a.Fungsi FROM tbluser a WHERE a.Username = ? AND a.Aktif = 'Aktif'";
        
        try {
                ps = conn.prepareStatement(query);
                ps.setString(1, username);
                rs = ps.executeQuery();
                if (rs.next()) {
                    DBHash = rs.getString(1);
                    id = rs.getString(2);
                    fungsi = rs.getString(3);
                    UserID.setUserLogin(tflUsername.getText()); 
                    UserID.setId(id);
                } 
        } catch (SQLException ex) {
                Logger.getLogger(FrmLoginMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        if (DBHash.equals(enteredHash)) {
            if (fungsi.equals("Manager Food Court")) {
            FrmLoginManagerFC fr = new FrmLoginManagerFC(id);
            fr.setVisible(true);
            this.dispose();
            } else if (fungsi.equals("Manager Vendor")) {
                FrmLoginManagerVendor fr = new FrmLoginManagerVendor(id);
                fr.setVisible(true);
                this.dispose();
            } else if (fungsi.equals("Kasir")) {
                FrmLoginKasir fr = new FrmLoginKasir(id);
                fr.setVisible(true);
                this.dispose();
            } else if (fungsi.equals("Pelayan")) {
                FrmLoginPelayan fr = new FrmLoginPelayan();
                fr.setVisible(true);
                this.dispose();
            } else if (fungsi.equals("Dapur")){
                FrmLoginDapur fr = new FrmLoginDapur(id);
                fr.setVisible(true);
                this.dispose();
            }
        } else
            JOptionPane.showMessageDialog(this, "Username/Password tidak ditemukan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        tflUsername = new javax.swing.JTextField();
        pflPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI FOODCOURT");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 280, 40));

        jPanel2.setBackground(new java.awt.Color(51, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Username :");
        jPanel2.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Password :");
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 80));

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(153, 0, 0));
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        btnMasuk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMasuk.setForeground(new java.awt.Color(153, 0, 0));
        btnMasuk.setText("MASUK");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        tflUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(tflUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 223, -1));

        pflPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pflPassword.setToolTipText("");
        pflPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pflPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(pflPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 223, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FoodCourt_logo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 390, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background foodcourt.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        login();        
    }//GEN-LAST:event_btnMasukActionPerformed

    private void pflPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pflPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10) {
            login();
        }
    }//GEN-LAST:event_pflPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pflPassword;
    private javax.swing.JTextField tflUsername;
    // End of variables declaration//GEN-END:variables
}
