/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasifoodcourt;

/**
 *
 * @author Windows 7
 */
public class FrmLoginManagerVendor extends javax.swing.JFrame {

    /**
     * Creates new form LoginManagerFC
     */
    
    String vid;
    public FrmLoginManagerVendor() {
        initComponents();
    }
    
    public FrmLoginManagerVendor(String id) {
        initComponents();
        vid = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEntryMenu = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnLaporanMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGER FOODCOURT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 574, -1));

        btnEntryMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEntryMenu.setText("ENTRY MENU");
        btnEntryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntryMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntryMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 158, 50));

        btnLaporan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLaporan.setText("LAPORAN PENDAPATAN");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 52));

        btnLaporanMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLaporanMenu.setText("LAPORAN PENJUALAN TIAP MENU");
        btnLaporanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaporanMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 250, 53));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/j.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 500, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        FrmLoginMaster fr = new FrmLoginMaster();
        fr.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnEntryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntryMenuActionPerformed
        // TODO add your handling code here:
        FrmMenu fr = new FrmMenu(vid);
        fr.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnEntryMenuActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        FrmLaporanVendor fr = new FrmLaporanVendor();
        fr.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnLaporanMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanMenuActionPerformed
        // TODO add your handling code here:
        FrmLaporanVendor2 fri = new FrmLaporanVendor2();
        fri.setVisible(true);
    }//GEN-LAST:event_btnLaporanMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginManagerVendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginManagerVendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntryMenu;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLaporanMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
