/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasifoodcourt;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author Syabith
 */
public class FrmPegawai extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public void lebarKolom(){
        TableColumn column;
        tblPegawai.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tblPegawai.getColumnModel().getColumn(0);
        column.setPreferredWidth(80);
        column = tblPegawai.getColumnModel().getColumn(1);
        column.setPreferredWidth(150);     
        column = tblPegawai.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
        column = tblPegawai.getColumnModel().getColumn(3);
        column.setPreferredWidth(90);
        column = tblPegawai.getColumnModel().getColumn(4);
        column.setPreferredWidth(140);  
        column = tblPegawai.getColumnModel().getColumn(5);
        column.setPreferredWidth(60);
    }

    Connection conn;
    PreparedStatement ps;
    int ctr;
    Statement st;
    ResultSet rs;
    private DefaultTableModel model;

    public FrmPegawai() {
        initComponents();
        
        model = new DefaultTableModel ( );
        tblPegawai.setModel(model);
        tblPegawai.setDefaultEditor(Object.class, null);
        model.addColumn("Id Pegawai");
        model.addColumn("Nama");
        model.addColumn("Username");
        model.addColumn("Gender");
        model.addColumn("Jabatan");
        model.addColumn("Aktif");
        try {
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcourt",
                    "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(FrmPegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshTable();
        lblKeterangan.setVisible(false);
    }
    
    private void resetField() {
        lblIdPegawai.setText("[ID]");
        tflNama.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        cbbJabatan.setSelectedIndex(-1);
        tflUsername.setText("");
        pflPassword.setText("");
        pflPassword1.setText("");
        lblKeterangan.setVisible(false);
    }
    
    private void refreshTable() {
        try { 
            model.setRowCount(0);
            String sql = "select a.IdPegawai, a.Nama, b.Username, a.Gender, a.Jabatan, a.Aktif from tblpegawai a, tblUser b "
                    + "WHERE a.IdPegawai = b.Id";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                });
            }
           tblPegawai.setModel(model);
           lebarKolom();
           rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmPegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tflCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbbJabatan = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIdPegawai = new javax.swing.JLabel();
        tflNama = new javax.swing.JTextField();
        rbtnPria = new javax.swing.JRadioButton();
        rbtnWanita = new javax.swing.JRadioButton();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tflUsername = new javax.swing.JTextField();
        pflPassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pflPassword1 = new javax.swing.JPasswordField();
        lblKeterangan = new javax.swing.JLabel();
        rbtntidakaktif = new javax.swing.JRadioButton();
        rbtnaktif = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Entry Data Pegawai"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entry Data Pegawai");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        tflCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tflCari.setToolTipText("Masukkan Nama");

        tblPegawai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPegawaiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPegawai);

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(tflCari, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tflCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tflCari.getAccessibleContext().setAccessibleDescription("");

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tabel Pegawai");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Pegawai:");

        cbbJabatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbbJabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager Food Court", "Kasir", "Pelayan" }));
        cbbJabatan.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jabatan:");

        lblIdPegawai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdPegawai.setText("[ID]");

        tflNama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        rbtnPria.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rbtnPria);
        rbtnPria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnPria.setText("Pria");

        rbtnWanita.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(rbtnWanita);
        rbtnWanita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnWanita.setText("Wanita");

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Username:");

        tflUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pflPassword.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Password:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Konfirm Password:");

        pflPassword1.setToolTipText("");

        lblKeterangan.setForeground(new java.awt.Color(153, 0, 51));
        lblKeterangan.setText("Kosongi Password jika tak diubah");

        rbtntidakaktif.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup2.add(rbtntidakaktif);
        rbtntidakaktif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtntidakaktif.setText("Tidak Aktif");

        rbtnaktif.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup2.add(rbtnaktif);
        rbtnaktif.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbtnaktif.setText("Aktif");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Aktif:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(39, 39, 39))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbtnPria)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbtnWanita))
                                .addComponent(tflNama, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(41, 41, 41)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbtnaktif)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbtntidakaktif))
                                .addComponent(cbbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tflUsername)
                            .addComponent(pflPassword)
                            .addComponent(pflPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblKeterangan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tflNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtnPria)
                    .addComponent(rbtnWanita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rbtnaktif)
                    .addComponent(rbtntidakaktif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKeterangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tflUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pflPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pflPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        try
        {
            st = conn.createStatement();
            String search = tflCari.getText();
            rs = st.executeQuery("SELECT a.IdPegawai, a.Nama, b.Username, a.Gender, a.Jabatan, a.Aktif from tblpegawai a, tblUser b "
                    + "WHERE a.IdPegawai = b.Id AND (a.IdPegawai like '%" + search + "%' OR a.Nama like '%"
                    +search+ "%' OR a.Gender like '%" + search + "%' OR a.Jabatan like '%" + search + "%' OR b.Username like '%"
                    +search+ "%')");
            model = (DefaultTableModel) tblPegawai.getModel();

            model.setRowCount(0);
            String [] data = new String[6];

            while(rs.next())
            {
                data[0] = rs.getString("IdPegawai");
                data[1] = rs.getString("Nama");
                data[2] = rs.getString("Username");
                data[3] = rs.getString("Gender");
                data[4] = rs.getString("Jabatan");
                data[5] = rs.getString("Aktif");
                model.addRow(data);
            }
            rs.close();
        }
        catch(SQLException ex)  {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
            System.err.println("error (search) : " +ex);
        }                          

    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        if (lblIdPegawai.getText().equals("[ID]")) {
            JOptionPane.showMessageDialog(this, "Pilih Pegawai untuk diupdate");
        } else {
            String kode, id, fungsi, username, password, kpassword, kodeterakhir;
            String nama, gender, jabatan, aktif;
            String hash = "";
            kode = lblIdPegawai.getText();
            id = kode;
            nama = tflNama.getText();
            gender = (rbtnPria.isSelected()) ? "Pria" : "Wanita";
            jabatan = cbbJabatan.getSelectedItem().toString();
            fungsi = jabatan;
            username = tflUsername.getText();
            password = new String(pflPassword.getPassword());
            kpassword = new String(pflPassword1.getPassword());
            if(rbtnaktif.isSelected()){
                aktif = "Aktif";
            }else{
                aktif = "Tidak Aktif";
            }
            try {
                if(password.equals("")) {
                    String query = "UPDATE tblpegawai SET Nama = ?, Gender = ?, Jabatan = ?, Aktif = ? WHERE IdPegawai = ?";
                    ps = conn.prepareStatement(query);
                    ps.setString(1, nama);
                    ps.setString(2, gender);
                    ps.setString(3, jabatan);
                    ps.setString(4, aktif);
                    ps.setString(5, kode);
                    
                    int pilihan = JOptionPane.showConfirmDialog(this, "Anda Yakin ingin mengupdate pegawai " + kode, "Konfirmasi",JOptionPane.YES_NO_OPTION);
                    if (pilihan == JOptionPane.YES_OPTION) {
                        ps.executeUpdate();
                        
                        //Mendapatkan IdUser
                        query = "SELECT IdUser FROM tblUser WHERE Id = '"+kode+"'";
                        st = conn.createStatement();
                        rs = st.executeQuery(query);
                        rs.next();
                        kode = rs.getString(1);
                        
                        query = "UPDATE tbluser SET Username = ?, Id = ?, Fungsi = ?, Aktif = ? WHERE IdUser = ?";
                        ps = conn.prepareStatement(query);
                        ps.setString(1, username);
                        ps.setString(2, id);
                        ps.setString(3, fungsi);
                        ps.setString(4, aktif);
                        ps.setString(5, kode);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Pegawai berhasil diupdate");
                    }
                    
                } else if(!password.equals(kpassword)) {
                    JOptionPane.showMessageDialog(this, "Konfirmasi Password tidak sama");
                    return;
                } else {
                    String query = "UPDATE tblpegawai SET Nama = ?, Gender = ?, Jabatan = ?, Aktif = ? WHERE IdPegawai = ?";
                    ps = conn.prepareStatement(query);
                    ps.setString(1, nama);
                    ps.setString(2, gender);
                    ps.setString(3, jabatan);
                    ps.setString(4, aktif);
                    ps.setString(5, kode);
                    
                    int pilihan = JOptionPane.showConfirmDialog(this, "Anda Yakin ingin mengupdate pegawai " + kode, "Konfirmasi",JOptionPane.YES_NO_OPTION);
                    if (pilihan == JOptionPane.YES_OPTION) {
                        ps.executeUpdate();
                        
                        //Mendapatkan IdUser
                        query = "SELECT IdUser FROM tblUser WHERE Id = '"+kode+"'";
                        st = conn.createStatement();
                        rs = st.executeQuery(query);
                        rs.next();
                        kode = rs.getString(1);
                        
                        MessageDigest md;
                        try {
                            md = MessageDigest.getInstance("MD5");
                            md.update(password.getBytes());
                            byte[] digest = md.digest();
                            hash = DatatypeConverter.printHexBinary(digest).toUpperCase();
                        } catch (NoSuchAlgorithmException ex) {
                            Logger.getLogger(FrmUser.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        query = "UPDATE tbluser SET Username = ?, Password = ?, Id = ?, Fungsi = ?, Aktif = ? WHERE IdUser = ?";
                        ps = conn.prepareStatement(query);
                        ps.setString(1, username);
                        ps.setString(2, hash);
                        ps.setString(3, id);
                        ps.setString(4, fungsi);
                        ps.setString(5, aktif);
                        ps.setString(6, kode);
                        ps.executeUpdate();
                        
                        JOptionPane.showMessageDialog(this, "Pegawai berhasil diupdate");
                    }
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrmPegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            resetField();
            refreshTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblPegawaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPegawaiMousePressed
        // TODO add your handling code here:
        int baris;
        String kode, nama, username, gender, jabatan, aktif;
        baris = tblPegawai.getSelectedRow();
        
        kode = tblPegawai.getModel().getValueAt(baris,0).toString();
        nama = tblPegawai.getModel().getValueAt(baris,1).toString();
        username = tblPegawai.getModel().getValueAt(baris,2).toString();
        gender = tblPegawai.getModel().getValueAt(baris,3).toString();
        jabatan = tblPegawai.getModel().getValueAt(baris,4).toString();
        aktif = tblPegawai.getModel().getValueAt(baris,5).toString();
        lblIdPegawai.setText(kode);
        tflNama.setText(nama);
        if (gender.equals("Pria"))
            rbtnPria.setSelected(true);
        else
            rbtnWanita.setSelected(true);
        cbbJabatan.setSelectedItem(jabatan);
        tflUsername.setText(username);
        pflPassword.setText("");
        pflPassword1.setText("");
        lblKeterangan.setVisible(true);
        if("Aktif".equals(tblPegawai.getModel().getValueAt(baris, 5).toString())){
            rbtnaktif.setSelected(true);
        }else{
            rbtntidakaktif.setSelected(true);
        }
    }//GEN-LAST:event_tblPegawaiMousePressed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nama, gender, jabatan, aktif;
        String kode, id, fungsi, username, password, kpassword, kodeterakhir;
        String hash = "";
        password = new String(pflPassword.getPassword());
        kpassword = new String(pflPassword1.getPassword());
        jabatan = cbbJabatan.getSelectedItem().toString();
        nama = tflNama.getText();
        gender = (rbtnPria.isSelected()) ? "Pria" : "Wanita";
        if(rbtnaktif.isSelected()){
            aktif = "Aktif";
        }else{
            aktif = "Tidak Aktif";
        }
        int jum = 1001;
        if(!password.equals(kpassword)) {
            JOptionPane.showMessageDialog(this, "Konfirmasi Password tidak sama");
        } else {
                
            try {
                username = tflUsername.getText();
                st = conn.createStatement();
                rs = st.executeQuery("SELECT Username FROM tbluser WHERE Username = '" + username + "'");
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Username sudah terpakai");
                } else {
                    //Ambil Kode Pegawai Terakhir
                    st = conn.createStatement();
                    rs = st.executeQuery("SELECT IdPegawai FROM tblpegawai ORDER BY IdPegawai DESC LIMIT 1");
                    rs.next();
                    kodeterakhir = rs.getString(1);
                    jum += Integer.parseInt(kodeterakhir.substring(1));
                    rs.close();
                    
                    // Tambah ke tabel pegawai
                    kode = "P" + String.valueOf(jum).substring(1);

                    String query = "INSERT INTO tblpegawai VALUES (?,?,?,?,?)";
                    
                    ps = conn.prepareStatement(query);
                    ps.setString(1, kode);
                    ps.setString(2, nama);
                    ps.setString(3, gender);
                    ps.setString(4, jabatan);
                    ps.setString(5, aktif);
                    ps.executeUpdate();        
                    
                    //Ambil kode user terakhir
                    id = kode;
                    fungsi = jabatan;
                    jum = 1001;

                    st = conn.createStatement();
                    rs = st.executeQuery("SELECT IdUser FROM tbluser ORDER BY IdUser DESC LIMIT 1");
                    rs.next();
                    kodeterakhir = rs.getString(1);
                    jum += Integer.parseInt(kodeterakhir.substring(1));
                    rs.close();
                    kode = "U" + String.valueOf(jum).substring(1);
                    
                    //Password Hashing
                    MessageDigest md;
                    try {
                        md = MessageDigest.getInstance("MD5");
                        md.update(password.getBytes());
                        byte[] digest = md.digest();
                        hash = DatatypeConverter.printHexBinary(digest).toUpperCase();
                    } catch (NoSuchAlgorithmException ex) {
                        Logger.getLogger(FrmUser.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    query = "INSERT INTO tbluser VALUES (?,?,?,?,?,?)";
                    
                    ps = conn.prepareStatement(query);
                    ps.setString(1, kode);
                    ps.setString(2, username);
                    ps.setString(3, hash);
                    ps.setString(4, id);
                    ps.setString(5, fungsi);
                    ps.setString(6, "Aktif");
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Pegawai berhasil ditambahkan");
                    //JOptionPane.showMessageDialog(this, "User berhasil ditambahkan");
                    
                    resetField();
                    refreshTable();
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrmUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
    */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdPegawai;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JPasswordField pflPassword;
    private javax.swing.JPasswordField pflPassword1;
    private javax.swing.JRadioButton rbtnPria;
    private javax.swing.JRadioButton rbtnWanita;
    private javax.swing.JRadioButton rbtnaktif;
    private javax.swing.JRadioButton rbtntidakaktif;
    private javax.swing.JTable tblPegawai;
    private javax.swing.JTextField tflCari;
    private javax.swing.JTextField tflNama;
    private javax.swing.JTextField tflUsername;
    // End of variables declaration//GEN-END:variables
}
