/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasifoodcourt;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Syabith
 */
public class FrmSiap extends javax.swing.JFrame {

    /**
     * Creates new form FrmDapurAntrian
     */
//        public void lebarKolom(){
//        TableColumn column;
//        tblAntrian.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
//        column = tblAntrian.getColumnModel().getColumn(0);
//        column.setPreferredWidth(200);
//        column = tblAntrian.getColumnModel().getColumn(1);
//        column.setPreferredWidth(150);     
//        column = tblAntrian.getColumnModel().getColumn(2);
//        column.setPreferredWidth(155);
//        column = tblAntrian.getColumnModel().getColumn(3);
//        column.setPreferredWidth(200);
//     }
    
    Connection conn;
    PreparedStatement ps;
    int ctr;
    Statement st;
    ResultSet rs;
    private DefaultTableModel model;    
    DefaultTableModel dtm;
    ArrayList<String[]> arrAntrian;
    Timer timer;
    
    public FrmSiap() {
        initComponents();
        
        model = new DefaultTableModel ( );
        tblAntrian.setModel(model);
        tblAntrian.setDefaultEditor(Object.class, null);
        model.addColumn("Waktu Order");
        model.addColumn("Nama Order");
        model.addColumn("Jumlah");
        model.addColumn("Meja");
        arrAntrian = new ArrayList<>();
        setTanggalWaktu();
        
        try { 
            conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcourt",
                    "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(FrmSiap.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Timer untuk Notifikasi
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
            
                refreshTable();
            }
        }, 100, 10*1000);
        
    }
    
    private void refreshTable() {
        model.setRowCount(0);
        arrAntrian.clear();
        String idPelayan = UserID.getId();
        String sql = "SELECT a.WaktuTransaksi, c.Nama, b.Jumlah, a.Meja, b.IdTransaksi, b.IdMenu "
                    + "FROM tbltransaksi a, tblrinciantransaksi b, tblmenu c "
                    + "WHERE a.IdTransaksi = b.IdTransaksi "
                    + "AND a.IdPelayan = '" + idPelayan + "'"
                    + "AND b.IdMenu = c.IdMenu "
                    + "AND b.Status = 'siap'";
        try {
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getTimestamp(1).toString(),
                    rs.getString(2),
                    rs.getInt(3),
                    rs.getInt(4)});
                    arrAntrian.add(new String[]{rs.getString(5), rs.getString(6)});
            }
           tblAntrian.setModel(model);
           
           
        } catch (SQLException ex) {
            Logger.getLogger(FrmSiap.class.getName()).log(Level.SEVERE, null, ex);
        }
//           lebarKolom(); 
    }
    
    private void setTanggalWaktu(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        java.text.SimpleDateFormat waktu = new java.text.SimpleDateFormat("HH:mm");
        lblTanggal.setText(kal.format(skrg));
        lblWaktu.setText(waktu.format(skrg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAntrian = new javax.swing.JTable();
        lblTanggal = new javax.swing.JLabel();
        lblWaktu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ready Order");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(469, 250));

        tblAntrian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAntrian.setGridColor(new java.awt.Color(0, 0, 0));
        tblAntrian.setPreferredSize(new java.awt.Dimension(300, 500));
        tblAntrian.setRowHeight(30);
        tblAntrian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAntrianMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblAntrian);

        lblTanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTanggal.setText("[Tanggal]");

        lblWaktu.setBackground(new java.awt.Color(0, 255, 51));
        lblWaktu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWaktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWaktu.setText("[Waktu]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWaktu)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWaktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblAntrianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAntrianMousePressed
        // TODO add your handling code here:
        int baris, jumlah, meja;
        String nama, IdTransaksi, IdMenu;
        baris = tblAntrian.getSelectedRow();
        if (baris != -1) {
            nama = tblAntrian.getModel().getValueAt(baris,1).toString();
            jumlah = (int)tblAntrian.getModel().getValueAt(baris,2);
            meja = (int)tblAntrian.getModel().getValueAt(baris,3);

            int pilihan = JOptionPane.showConfirmDialog(this, "Konfirmasi "+ jumlah
                    + " " + nama + " untuk Meja " + meja + " sudah disajikan",
                        "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (pilihan == JOptionPane.YES_OPTION) {
                    IdTransaksi = arrAntrian.get(baris)[0];
                    IdMenu = arrAntrian.get(baris)[1];
                    String sql = "UPDATE tblrinciantransaksi SET Status = 'tersajikan' "
                            + "WHERE IdTransaksi = ? AND IdMenu = ?";
                    try {
                        ps = conn.prepareStatement(sql);
                        ps.setString(1, IdTransaksi);
                        ps.setString(2, IdMenu);
                        ps.executeUpdate();
                        refreshTable();
                    } catch (SQLException ex) {
                        Logger.getLogger(FrmSiap.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
//        lebarKolom();
    }//GEN-LAST:event_tblAntrianMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        FrmLoginPelayan fr = new FrmLoginPelayan();
        fr.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSiap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSiap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSiap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSiap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSiap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JTable tblAntrian;
    // End of variables declaration//GEN-END:variables
}
